version: '2'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - env.mysql
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "7"
    privileged: true

  yourls:
    # replace "image" with "build" for developing purpose
    # build: ./
    image: guessi/docker-yourls:1.7.2
    links:
      - mysql:mysql
    env_file:
      - env.yourls
    ports:
      - 80:80
    depends_on:
      - mysql
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "7"
